apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: taco-cluster
  namespace: taco-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 193.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: OpenStackCluster
    name: taco-cluster
    namespace: taco-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: OpenStackCluster
metadata:
  name: taco-cluster
  namespace: taco-cluster
spec:
  cloudName: taco-openstack
  cloudsSecret:
    name: cloud-config
    namespace: taco-cluster
  disablePortSecurity: true
  disableServerTags: true
  dnsNameservers: []
  externalNetworkId: 7fcc5652-4e98-4cec-9072-acaa2662c519
  network: 
    name: private-net
  nodeCidr: ""
